repos:
  # Common fixers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.3.0'
    hooks: []

  # Keep dependencies in this file in sync with dev dependencies in pyproject.toml
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: '1.1.0'
    hooks:
      - id: sync_with_poetry
        args: [ ]

  # Format Python code to black standards
  - repo: https://github.com/psf/black
    rev: '23.12.1'
    hooks:
      - id: black

  # Standardise ordering of Python imports
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort

  # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.286'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        language: system
        args: [--check-untyped-defs]

  # Poetry sync - pulls versions of lib from poetry dev versions so precommit stays in sync
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "1.1.0" # the revision or tag to clone at
    hooks:
      - id: sync_with_poetry
        args: [ ] # optional args
